<?php

namespace Database\Seeders;

use App\Models\AttendanceMeeting;
use App\Models\AttendanceSection;
use App\Models\Questionnaire;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class EvaluationC7Seeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // evaluation_forms
        DB::unprepared('SET IDENTITY_INSERT evaluation_forms ON');

        DB::table('evaluation_forms')->insert([
            [
                'id' => 7,
                'pdf_template_id' => 2,
                'shortcode' => 'C7',
                'title' => 'BOT EVALUATION FORM C.7 – LEAD RESOURCE PERSONS (LRPs)',
                'created_at' => now(),
                'updated_at' => now(),
            ]
        ]);

        DB::unprepared('SET IDENTITY_INSERT evaluation_forms OFF');


        // evaluation_form_sections (performance section)
        DB::unprepared('SET IDENTITY_INSERT evaluation_form_sections ON');

        DB::table('evaluation_form_sections')->insert([
            [
                'id' => 13,
                'evaluation_form_id' => 7,
                'rating_scale_id' => 1,
                'section_type_id' => 1,
                'title' => 'Committee Performance (to be rated by all voting members of the concerned BOT Committee) - 70 %',
                'add_remarks' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ]
        ]);

        DB::unprepared('SET IDENTITY_INSERT evaluation_form_sections OFF');


        Questionnaire::insert([
            ['section_id' => 13, 'name' => 'Active and constructive participation in Committee meetings.'],
            ['section_id' => 13, 'name' => 'Professionalism displayed during Committee discussions.'],
            ['section_id' => 13, 'name' => 'Competence displayed during presentations and Committee discussions.'],
            ['section_id' => 13, 'name' => 'Level of diligence manifested in preparing for Committee meetings.'],
            ['section_id' => 13, 'name' => 'Expertise on the subject matter for which their presence is sought.'],
            ['section_id' => 13, 'name' => 'Ability to render independent judgment on matters falling within their areas of expertise.'],
            ['section_id' => 13, 'name' => 'Efficiency manifested in complying with matters arising from Committee meetings.'],
            ['section_id' => 13, 'name' => 'Quality of proposals and presentations made before the Committee meeting.'],
            ['section_id' => 13, 'name' => 'Value-added benefit generated by their presence during Committee meetings.'],
            ['section_id' => 13, 'name' => 'Observance of proper protocol during Committee meetings.'],
        ]);


        // evaluation_form_sections (attendance section)
        DB::unprepared('SET IDENTITY_INSERT evaluation_form_sections ON');

        DB::table('evaluation_form_sections')->insert([
            [
                'id' => 14,
                'evaluation_form_id' => 7,
                'rating_scale_id' => 2,
                'section_type_id' => 2,
                'title' => 'Attendance to Committee Meetings (to be rated by the Corporate Secretary) -30 % ',
                'add_remarks' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ]
        ]);

        DB::unprepared('SET IDENTITY_INSERT evaluation_form_sections OFF');


        // attendance_sections
        DB::unprepared('SET IDENTITY_INSERT attendance_sections ON');

        AttendanceSection::insert([
            [
                'id' => 7,
                'section_id' => 14,
                'show_total_meetings' => true,
                'show_physically_present' => false,
                'show_considered_present' => false,
                'show_total_present' => true,
                'show_attendance_rating' => true,
            ]
        ]);

        DB::unprepared('SET IDENTITY_INSERT attendance_sections OFF');


        AttendanceMeeting::insert([
            ['attendance_section_id' => 7, 'name' => 'Governance Committee'],
            ['attendance_section_id' => 7, 'name' => 'Risk Oversight'],
            ['attendance_section_id' => 7, 'name' => 'Audit & Compliance'],
            ['attendance_section_id' => 7, 'name' => 'Human Resource'],
            ['attendance_section_id' => 7, 'name' => 'Credit & Collection'],
            ['attendance_section_id' => 7, 'name' => 'Membership & Amendment'],
            ['attendance_section_id' => 7, 'name' => 'ITSC'],
        ]);
    }
}
