<?php

namespace Database\Seeders;

use App\Models\AttendanceMeeting;
use App\Models\AttendanceSection;
use App\Models\EvaluationForm;
use App\Models\EvaluationFormSection;
use App\Models\Questionnaire;
use Illuminate\Database\Seeder;

class EvaluationC7Seeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $c7 = EvaluationForm::create([
            "pdf_template_id" => 2,
            "shortcode" => "C7",
            "title" => "BOT EVALUATION FORM C.7 – LEAD RESOURCE PERSONS (LRPs)",
            "created_at" => now(),
            "updated_at" => now(),
        ]);

        $performanceSection = EvaluationFormSection::create([
            "evaluation_form_id" => $c7->id,
            "rating_scale_id" => 1,
            "section_type_id" => 1,
            "title" => "Committee Performance (to be rated by all voting members of the concerned BOT Committee) - 70 %",
            "add_remarks" => false,
            "created_at" => now(),
            "updated_at" => now(),
        ]);

        Questionnaire::insert([
            ["section_id" => $performanceSection->id, "name" => "Active and constructive participation in Committee meetings."],
            ["section_id" => $performanceSection->id, "name" => "Professionalism displayed during Committee discussions."],
            ["section_id" => $performanceSection->id, "name" => "Competence displayed during presentations and Committee discussions."],
            ["section_id" => $performanceSection->id, "name" => "Level of diligence manifested in preparing for Committee meetings."],
            ["section_id" => $performanceSection->id, "name" => "Expertise on the subject matter for which their presence is sought."],
            ["section_id" => $performanceSection->id, "name" => "Ability to render independent judgment on matters falling within their areas of expertise."],
            ["section_id" => $performanceSection->id, "name" => "Efficiency manifested in complying with matters arising from Committee meetings."],
            ["section_id" => $performanceSection->id, "name" => "Quality of proposals and presentations made before the Committee meeting."],
            ["section_id" => $performanceSection->id, "name" => "Value-added benefit generated by their presence during Committee meetings."],
            ["section_id" => $performanceSection->id, "name" => "Observance of proper protocol during Committee meetings."],
        ]);

        $attendanceFormSection = EvaluationFormSection::create([
            "evaluation_form_id" => $c7->id,
            "rating_scale_id" => 2,
            "section_type_id" => 2,
            "title" => "Attendance to Committee Meetings (to be rated by the Corporate Secretary) -30 % ",
            "add_remarks" => false,
            "created_at" => now(),
            "updated_at" => now(),
        ]);

        $attendanceSection = AttendanceSection::create([
            "section_id" => $attendanceFormSection->id,
            "show_total_meetings" => true,
            "show_physically_present" => false,
            "show_considered_present" => false,
            "show_total_present" => true,
            "show_attendance_rating" => true,
        ]);

        AttendanceMeeting::insert([
            ["attendance_section_id" => $attendanceSection->id, "name" => "Governance Committee"],
            ["attendance_section_id" => $attendanceSection->id, "name" => "Risk Oversight"],
            ["attendance_section_id" => $attendanceSection->id, "name" => "Audit & Compliance"],
            ["attendance_section_id" => $attendanceSection->id, "name" => "Human Resource"],
            ["attendance_section_id" => $attendanceSection->id, "name" => "Credit & Collection"],
            ["attendance_section_id" => $attendanceSection->id, "name" => "Membership & Amendment"],
            ["attendance_section_id" => $attendanceSection->id, "name" => "ITSC"],
        ]);
    }
}
