<?php

namespace App\Filament\Resources\Trustees\Pages;

use App\Filament\Resources\Trustees\TrusteeResource;
use App\Models\Trustee;
use App\Models\User;
use Filament\Resources\Pages\CreateRecord;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Facades\DB;
use Spatie\Permission\Models\Role;

class CreateTrustee extends CreateRecord
{
    protected static string $resource = TrusteeResource::class;

    protected function handleRecordCreation(array $data): Model
    {

        $user = User::create([
            'name' => $data['first_name'] . ' ' . $data['last_name'],
            'is_active' => $data['is_active'],
            'first_name' => $data['first_name'],
            'last_name' => $data['last_name'],
            'middle_name' => $data['middle_name'],
            'suffix' => $data['suffix'],
            'email' => $data['email'],
            'password' => bcrypt($data['password']),
        ]);

        DB::table('model_has_roles')->insert([
            'role_id' => Role::where('name', 'Trustee')->first()->id,
            'model_id' => $user->id,
            'model_type' => User::class,
        ]);

        unset($data['is_active'], $data['first_name'], $data['last_name'], $data['middle_name'], $data['suffix'], $data['email'], $data['password']);

        $data['user_id'] = $user->id;

        return parent::handleRecordCreation($data); // TODO: Change the autogenerated stub
    }
}
