<?php

namespace App\Filament\Resources\Trustees\Pages;

use App\Filament\Resources\Trustees\TrusteeResource;
use App\Models\User;
use Filament\Actions\DeleteAction;
use Filament\Actions\ViewAction;
use Filament\Resources\Pages\EditRecord;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Facades\DB;
use Spatie\Permission\Models\Role;

class EditTrustee extends EditRecord
{
    protected static string $resource = TrusteeResource::class;

    protected function getHeaderActions(): array
    {
        return [
            DeleteAction::make(),
        ];
    }

    protected function mutateFormDataBeforeFill(array $data): array
    {
        $user = $this->record->user;
        $data['is_active'] = $user->is_active;
        $data['first_name'] = $user->first_name;
        $data['last_name'] = $user->last_name;
        $data['middle_name'] = $user->middle_name;
        $data['suffix'] = $user->suffix;
        $data['email'] = $user->email;
        return $data;
    }

    protected function handleRecordUpdate(Model $record, array $data): Model
    {
       $record->user->update([
            'name' => $data['first_name'] . ' ' . $data['last_name'],
            'is_active' => $data['is_active'],
            'first_name' => $data['first_name'],
            'last_name' => $data['last_name'],
            'middle_name' => $data['middle_name'],
            'suffix' => $data['suffix'],
            'email' => $data['email'],
            'password' => bcrypt($data['password']),
        ]);

        unset($data['is_active'], $data['first_name'], $data['last_name'], $data['middle_name'], $data['suffix'], $data['email'], $data['password']);

        return parent::handleRecordUpdate($record, $data); // TODO: Change the autogenerated stub
    }
}
