<?php

namespace App\Filament\Resources\Committees\Pages;

use App\Filament\Resources\Committees\CommitteeResource;
use App\Models\CommitteeHasTrustee;
use App\Models\EvaluationPeriod;
use App\Models\User;
use BackedEnum;
use Filament\Actions\ViewAction;
use Filament\Resources\Pages\ListRecords;
use Filament\Support\Icons\Heroicon;
use Filament\Tables\Columns\TextColumn;
use Filament\Tables\Table;
use Illuminate\Database\Eloquent\Builder;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\Relation;
use Spatie\Permission\Models\Role;

class EvaluationPeriods extends ListRecords
{
    protected static string $resource = CommitteeResource::class;

    public $record,$evaluator_id;
    protected $queryString = ['record','evaluator_id','evaluation_id'];
    protected static ?string $title = 'Evaluation Period';

    public function getBreadcrumb(): ?string
    {
        $evaluator = User::find($this->evaluator_id);
        return $evaluator->fullname.' | Evaluation Periods'; // TODO: Change the autogenerated stub
    }

    protected static string|BackedEnum|null $navigationIcon = Heroicon::OutlinedRectangleStack;

    protected function getTableQuery(): Builder|Relation|null
    {
        return EvaluationPeriod::query()
            ->whereHas('assignments', function ($query) {
                $query->where('evaluator_id', $this->evaluator_id);
            })->with('assignments');
    }


    public function table(Table $table): Table
    {
        return $table
            ->columns([
                TextColumn::make('id'),
                TextColumn::make('status.name'),
                TextColumn::make('date_from')->dateTime(),
                TextColumn::make('date_to')->dateTime(),
            ])
            ->filters([
                //
            ])
            ->headerActions([
            ])
            ->recordActions([
                ViewAction::make()
                    ->authorize(function (): bool {
                        if(auth()->user()->hasPermissionTo('FullAccess:Committee')) return true;

                        $committee_id = $this->getOwnerRecord()->id;
                        $user_id = auth()->user()->id;
                        $role_id = CommitteeHasTrustee::where('committee_id', $committee_id)
                            ->where('user_id', $user_id)
                            ->first()?->role_id;

                        $role = Role::where('id', $role_id)->first();
                        return $role->hasPermissionTo('View:Committee');
                    })
                    ->url(fn(Model $record): string => CommitteeResource::getUrl('evaluation-members', ['record' => $this->record,'evaluator_id' => $this->evaluator_id,'evaluation_id' => $record->id])),
            ])
            ->toolbarActions([
//                BulkActionGroup::make([
//                    DetachBulkAction::make(),
//                    DeleteBulkAction::make(),
//                ]),
            ]);
    }
}
