<?php

namespace App\Filament\Resources\Meetings\Pages;

use App\Filament\Resources\Meetings\MeetingResource;
use App\Models\MeetingAttendee;
use Filament\Resources\Pages\CreateRecord;
use Illuminate\Database\Eloquent\Model;

class CreateMeeting extends CreateRecord
{
    protected static string $resource = MeetingResource::class;

    protected function handleRecordCreation(array $data): Model
    {

        if($data['committee_id'] == 'bot_meetings'){
            $data['committee_id'] = null;
        }

        $data['created_by'] = auth()->id();

        return parent::handleRecordCreation($data); // TODO: Change the autogenerated stub
    }

    protected function afterCreate(): void
    {
        $attendees = collect($this->data['attendees'])->map(fn ($user_id) => [
            'meeting_id'  => $this->record->id,
            'user_id'     => $user_id,
            'committee_id' => $this->record->committee_id,
        ]);

        MeetingAttendee::insert($attendees->toArray());
    }

}
