<?php

namespace App\Filament\Resources\Meetings\Pages;

use App\Filament\Resources\Meetings\MeetingResource;
use Filament\Resources\Pages\CreateRecord;
use Illuminate\Database\Eloquent\Model;

class CreateMeeting extends CreateRecord
{
    protected function handleRecordCreation(array $data): Model
    {
        $data['created_by'] = auth()->id();
        return parent::handleRecordCreation($data); // TODO: Change the autogenerated stub
    }

    protected static string $resource = MeetingResource::class;
}
