<?php

namespace App\Filament\Resources\Meetings\Pages;

use App\Filament\Resources\Meetings\MeetingResource;
use App\Models\MeetingAttendee;
use Filament\Actions\DeleteAction;
use Filament\Actions\ViewAction;
use Filament\Resources\Pages\EditRecord;
use Illuminate\Database\Eloquent\Model;

class EditMeeting extends EditRecord
{
    protected static string $resource = MeetingResource::class;

    protected function getHeaderActions(): array
    {
        return [
            ViewAction::make(),
            DeleteAction::make(),
        ];
    }

    protected function handleRecordUpdate(Model $record, array $data): Model
    {
        if($data['committee_id'] == 'bot_meetings'){
            $data['committee_id'] = null;
        }

        return parent::handleRecordUpdate($record, $data); // TODO: Change the autogenerated stub
    }

    protected function mutateFormDataBeforeFill(array $data): array
    {
        $data['attendees'] = $this->record->attendees->pluck('user_id')->toArray();

        if($data['committee_id'] == null){
            $data['committee_id'] = 'bot_meetings';
        }

        return parent::mutateFormDataBeforeFill($data); // TODO: Change the autogenerated stub
    }

    protected function afterSave(): void
    {
        $selected = $this->data['attendees'] ?? [];

        $this->record->attendees()->delete();

        $attendees = collect($selected)->map(fn ($user_id) => [
            'meeting_id'   => $this->record->id,
            'user_id'      => $user_id,
            'committee_id' => $this->record->committee_id,
            'created_at'   => now(),
            'updated_at'   => now(),
        ]);

        MeetingAttendee::insert($attendees->toArray());

        $this->record->load('attendees');

        $this->dispatch('refreshAttendees');
    }
}
