<?php

namespace App\Livewire;

use App\Filament\Resources\Meetings\MeetingResource;
use App\Models\CalendarEventModel;
use App\Models\Meeting;
use Illuminate\Support\Facades\Auth;
use Saade\FilamentFullCalendar\Actions\CreateAction;
use Saade\FilamentFullCalendar\Actions\DeleteAction;
use Saade\FilamentFullCalendar\Actions\EditAction;
use Saade\FilamentFullCalendar\Widgets\FullCalendarWidget;

class CalendarWidget extends FullCalendarWidget
{
    /**
     * FullCalendar will call this function whenever it needs new event data.
     * This is triggered when the user clicks prev/next or switches views on the calendar.
     */
    public function fetchEvents(array $fetchInfo): array
    {
        $user = Auth::user();

        return Meeting::query()
            ->with(['meetingType'])
            ->where('scheduled_at', '>=', now())
            ->when(
                !$user->hasRole(['Super Admin', 'Secretariat']),
                fn ($query) => $query->whereHas('attendees', function ($q) use ($user) {
                    $q->where('user_id', $user->id); // ← change to your FK column
                })
            )
            ->get()
            ->map(function (Meeting $meeting) {

                $bgColor = $meeting->committee?->color ?? '#5b5d76';

                $textColor = $this->isReadableWithWhiteText($bgColor) ? '#ffffff' : '#111827';

                return [
                    'id' => $meeting->id,
                    'title' => $meeting->title,
                    'start' => $meeting->scheduled_at,
                    'end' => $meeting->scheduled_at->addHour(),
                    'allDay' => false,
                    'backgroundColor' => $bgColor,
                    'textColor' => $textColor,
                    'borderColor' => 'transparent',
                    'display' => 'block',
                    'url' => MeetingResource::getUrl('view', ['record' => $meeting->id]),
                    'shouldOpenUrlInNewTab' => true,
                ];

            })
            ->toArray();
    }

    public function config(): array
    {
        return [
            'firstDay' => 1,
            'headerToolbar' => [
                'right' => 'dayGridMonth,timeGridWeek,timeGridDay',
                'center' => 'title',
                'left' => 'prev,next today',
            ],
        ];
    }

    function isReadableWithWhiteText($hexColor) {

        $hex = ltrim($hexColor, '#');

        // Convert hex to decimal RGB values
        $r = hexdec(substr($hex, 0, 2));
        $g = hexdec(substr($hex, 2, 2));
        $b = hexdec(substr($hex, 4, 2));

        // Calculate YIQ brightness (human eye perception weight)
        $yiq = (($r * 299) + ($g * 587) + ($b * 114)) / 1000;

        // Return true if the background is dark enough for white text
        return ($yiq < 128);
    }

    public function eventDidMount(): string
    {

        return <<<JS
            function({ event, timeText, isStart, isEnd, isMirror, isPast, isFuture, isToday, el, view }){

            const formattedDate = event.start.toLocaleString(undefined, {
                  weekday: 'short',
                  hour: '2-digit',
                  minute: '2-digit'
             });

                el.setAttribute("x-tooltip", "tooltip");
                el.setAttribute("x-data", "{ tooltip: '"+formattedDate+" - "+event.title+"' }");
            }
        JS;
    }

    protected function headerActions(): array
    {
        return []; // TODO: Change the autogenerated stub
    }

}

